version: '3.11'

services:
  fastapi-lessons:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn "path_operations:app" --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"