version: '3.11'

services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn string_validations:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"